version: "3"

services:
  webhookproxy:
    image: _DOCKER_REGISTRY_/org.homelab.artifact.config-server:1.0.0-SNAPSHOT
    container_name: config-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "TZ=Europe/Amsterdam"
      - "LOGFILE_PATH=/volume/logs"
      - "LOGLEVEL_SPRING=_LOGLEVEL_SPRING_"
      - "LOGLEVEL_APPLICATION=_LOGLEVEL_APPLICATION_"
      - "LOGLEVEL_HIBERNATE=_LOGLEVEL_HIBERNATE_"
      - "ENCRYPTION_KEY=_ENCRYPTION_KEY_"
      - "DB_DRIVER_CLASS=_DB_DRIVER_CLASS_"
      - "DB_CONNECT_URL=_DB_CONNECT_URL_"
      - "DB_USERNAME=_DB_USERNAME_"
      - "DB_PASSWORD=_DB_PASSWORD_"
      - "SHOW_SQL=_SHOW_SQL_"
      - "DB_DIALECT=_DB_DIALECT_"
      - "H2_CONSOLE_ENABLED=_H2_CONSOLE_ENABLED_"
      - "DB_SCRIPTS_LOCATION=_DB_SCRIPTS_LOCATION_"
      - "CONFIG_SQL=_CONFIG_SQL_"
    volumes:
      - ./volume/logs:/volume/logs
    ports:
      - "_CONFIG_SERVER_PORT_:8888"
