version: "3"

services:
  webhookproxy:
    image: _DOCKER_REGISTRY_/config-server:1.0.0-SNAPSHOT
    container_name: config-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "TZ=Europe/Amsterdam"
      - "LOGFILE_PATH=/volume/logs"
      - "LOGLEVEL_SPRING=_LOGLEVEL_SPRING_"
      - "LOGLEVEL_APPLICATION=_LOGLEVEL_APPLICATION_"
      - "ENCRYPTION_KEY"
      - "DB_DRIVER_CLASS"
      - "DB_CONNECT_URL"
      - "DB_USERNAME"
      - "DB_PASSWORD"
      - "SHOW_SQL"
      - "DB_DIALECT"
      - "H2_CONSOLE_ENABLED"
      - "DB_SCRIPTS_LOCATION"
      - "CONFIG_SQL"
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
    volumes:
      - ./volume/logs:/volume/logs
    ports:
      - "_CONFIG_SERVER_PORT_:8888"
